language: ruby

rvm:
  - 2.3.3

jdk:
  - oraclejdk9

env:
  - URL=https://github.com/redpen-cc/redpen/releases/download/redpen-1.6.1

install:
  - wget $URL/redpen-1.6.1.tar.gz
  - tar xvf redpen-1.6.1.tar.gz
  - export PATH=$PATH:$PWD/redpen-distribution-1.6.1/bin

script:
  - gem install asciidoctor
  - gem install coderay
  - gem install --pre asciidoctor-pdf
  - make check     # Apply RedPen
  - make html      # Generate HTML document
